### ISSUE TITLE
[BE] : docker-compose v1

### ISSUE THREAD

**Issue by aihoshistar** [DDD-Community/DDD-10-WABLE-SERVER#57]
## 설명

* docker stack 에 사용할 docker-compose 파일 

## 진행사항

```yaml
 version: '3.8'

 services:
   ddd-api:
     image: ghcr.io/ddd-community/ddd-10-wable-server@sha256:8bc81bce9440e57b6fa4946b3f54afdf8f73bbbee2bbb05adb613b6abba4568e
     container_name: ddd-api
     environment:
       - ENCRYPTOR_PASSWORD=db039553-0376-4b92-ae75-27605da4f0b7
       - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/wable-server
     restart: always
     networks:
       - ddd
     deploy:
       replicas: 1
       restart_policy:
         condition: on-failure

 networks:
   ddd:
     external: true
     driver: overlay
```
